kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role-binding
  namespace: default
subjects:

# Kubernetes service account
- kind: User
  name: p.liedtke@student.vu.nl

roleRef:
  kind: CLusterRole
  name: developer
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-role-binding
  namespace: default

subjects:
# Kubernetes service account
  - kind: User
    name: s.mojzis@student.vu.nl

roleRef:
  kind: CLusterRole
  name: devops-engineer
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager-role-binding
  namespace: default
subjects:
# Kubernetes service account
  - kind: User
    name: g.savchenko@student.vu.nl
roleRef:
  kind: CLusterRole
  name: manager
  apiGroup: rbac.authorization.k8s.io