replicaCount: 3
frontendImage: gcr.io/diesel-dominion-375713/frontend:vp3
frontendTargetPort: 80
frontendPort: 8091
backendImage: gcr.io/diesel-dominion-375713/backend:vp1
backendTargetPort: 5000
backendPort: 8081
dbPort: 5432
dbURL: postgresql://postgresadmin:admin123@postgres-service.default.svc.cluster.local:5432/postgresdb
hostName: "<IP>.nip.io"
roles:
  managers: 
    - g.savchenko@student.vu.nl
  developers:
    - p.liedtke@student.vu.nl
  devops:
    - s.mojzis@student.vu.nl
