replicaCount: 3
frontendImage: gcr.io/diesel-dominion-375713/frontend:vp1
frontendTargetPort: 80
frontendPort: 8091
backendImage: gcr.io/diesel-dominion-375713/backend:vp1
backendTargetPort: 5000
backendPort: 8081
dbPort: 5432
hostName: "35.239.106.62.nip.io"